spring.application.name=order-payment-inventory-concurrency-lab
spring.datasource.url=jdbc:postgresql://localhost:5432/concurrency_lab
spring.datasource.username=admin
spring.datasource.password=admin12!@
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true
