spring:
  application:
    name: order-payment-inventory-concurrency-lab
  datasource:
    url: jdbc:postgresql://localhost:5432/concurrency_lab
    username: "admin"
    password: "admin12!@"
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
