create table products (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    price numeric(19, 2) not null,
    created_at timestamp,
    updated_at timestamp
);

create table inventories (
    id bigint generated by default as identity primary key,
    product_id bigint not null,
    quantity integer not null,
    created_at timestamp,
    updated_at timestamp,
    constraint fk_inventories_product_id foreign key (product_id) references products(id),
    constraint uk_inventories_product_id unique (product_id)
);

create index idx_inventories_product_id on inventories(product_id);
