create table customer_orders (
    id bigint generated by default as identity primary key,
    status varchar(20) not null,
    total_amount numeric(19, 2) not null,
    created_at timestamp,
    updated_at timestamp
);

create table order_items (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    product_id bigint not null,
    quantity integer not null,
    unit_price numeric(19, 2) not null,
    line_amount numeric(19, 2) not null,
    created_at timestamp,
    updated_at timestamp,
    constraint fk_order_items_order_id foreign key (order_id) references customer_orders(id)
);

create index idx_order_items_order_id on order_items(order_id);
create index idx_order_items_product_id on order_items(product_id);
