create table payments (
    id bigint generated by default as identity primary key,
    order_id bigint not null,
    amount numeric(19, 2) not null,
    status varchar(20) not null,
    failure_reason varchar(255),
    created_at timestamp not null,
    updated_at timestamp not null,
    constraint fk_payments_order_id foreign key (order_id) references customer_orders(id),
    constraint uk_payments_order_id unique (order_id)
);

create index idx_payments_order_id on payments(order_id);
